from value import common
from value.css import *


css_properties = {
    "-webkit-align-content": AlignContentValue,
    "-webkit-align-items": AlignItemsValue,
    "-webkit-align-self": AlignSelfValue,
    "-webkit-animation": AnimationValue,
    "-webkit-animation-delay": AnimationDelayValue,
    "-webkit-animation-direction": AnimationDirectionValue,
    "-webkit-animation-duration": AnimationDurationValue,
    "-webkit-animation-fill-mode": AnimationFillModeValue,
    "-webkit-animation-iteration-count": AnimationIterationCountValue,
    "-webkit-animation-name": AnimationNameValue,
    "-webkit-animation-play-state": AnimationPlayStateValue,
    "-webkit-animation-timing-function": AnimationTimingFunctionValue,
    # "-webkit-app-region": WebkitAppRegionValue,
    "-webkit-appearance": AppearanceValue,
    "-webkit-backface-visibility": BackfaceVisibilityValue,
    "-webkit-background-clip": BackgroundClipValue,
    "-webkit-background-origin": BackgroundOriginValue,
    "-webkit-background-size": BackgroundSizeValue,
    "-webkit-border-after": BorderValue,
    "-webkit-border-after-color": CSSColorValue,
    "-webkit-border-after-width": CSSLineWidthValue,
    "-webkit-border-before": BorderValue,
    "-webkit-border-before-color": CSSColorValue,
    "-webkit-border-before-style": BorderStyleValue,
    "-webkit-border-before-width": CSSLineWidthValue,
    "-webkit-border-bottom-left-radius": RadiusValue,
    "-webkit-border-bottom-right-radius": RadiusValue,
    "-webkit-border-end": BorderValue,
    "-webkit-border-end-color": CSSColorValue,
    "-webkit-border-end-width": CSSLineWidthValue,
    "-webkit-border-image": BorderImageValue,
    "-webkit-border-radius": BorderRadiusValue,
    "-webkit-border-start": BorderValue,
    "-webkit-border-start-color": CSSColorValue,
    "-webkit-border-start-width": CSSLineWidthValue,
    "-webkit-border-top-left-radius": RadiusValue,
    "-webkit-border-top-right-radius": RadiusValue,
    "-webkit-border-vertical-spacing": CSSLengthPercentageValue,
    "-webkit-box-align": BoxAlignValue,
    "-webkit-box-decoration-break": BoxDecorationBreakValue,
    "-webkit-box-direction": BoxDirectionValue,
    "-webkit-box-flex": common.NumberValue,
    "-webkit-box-flex-group": common.IntegerValue,
    "-webkit-box-lines": BoxLinesValue,
    "-webkit-box-ordinal-group": common.IntegerValue,
    "-webkit-box-orient": BoxOrientValue,
    "-webkit-box-pack": BoxPackValue,
    "-webkit-box-reflect": BoxReflectValue,
    "-webkit-box-shadow": BoxShadowValue,
    "-webkit-box-sizing": BoxSizingValue,
    "-webkit-clip-path": ClipPathValue,
    "-webkit-color-correction": WebkitColorCorrectionValue,
    "-webkit-column-break-after": ColumnBreakAfterValue,
    "-webkit-column-break-before": ColumnBreakAfterValue,
    "-webkit-column-break-inside": ColumnBreakAfterValue,
    "-webkit-column-count": ColumnCountValue,
    "-webkit-column-fill": ColumnFillValue,
    "-webkit-column-gap": ColumnGapValue,
    "-webkit-column-rule": BorderValue,
    "-webkit-column-rule-color": CSSColorValue,
    "-webkit-column-rule-style": BorderStyleValue,
    "-webkit-column-rule-width": CSSLineWidthValue,
    "-webkit-column-span": ColumnSpanValue,
    "-webkit-column-width": ColumnWidthValue,
    "-webkit-columns": ColumnsValue,
    "-webkit-direction": DirectionValue,
    "-webkit-filter": FilterValue,
    "-webkit-flex": FlexValue,
    "-webkit-flex-direction": FlexDirectionValue,
    "-webkit-flex-wrap": FlexWrapValue,
    "-webkit-flow-from": WebkitFlowFromValue,
    "-webkit-flow-into": WebkitFlowIntoValue,
    "-webkit-font-feature-settings": FontFeatureSettingsValue,
    "-webkit-font-smoothing": WebkitFontSmoothingValue,
    "-webkit-hyphenate-character": WebkitHyphenateCharacterValue,
    "-webkit-hyphens": HyphensValue,
    "-webkit-justify-content": JustifyContentValue,
    "-webkit-line-break": LineBreakValue,
    "-webkit-line-clamp": common.IntegerValue,
    "-webkit-locale": WebKitLocaleValue,
    "-webkit-logical-height": CSSLengthValue,
    "-webkit-logical-width": CSSLengthValue,
    "-webkit-margin-after": CSSLengthPercentageValue,
    "-webkit-margin-after-collapse": WebkitMarginAfterCollapseValue,
    "-webkit-margin-before": CSSLengthPercentageValue,
    "-webkit-margin-before-collapse": WebkitMarginAfterCollapseValue,
    "-webkit-margin-bottom-collapse": WebkitMarginAfterCollapseValue,
    "-webkit-margin-collapse": WebkitMarginCollapseValue,
    "-webkit-margin-end": CSSLengthPercentageValue,
    "-webkit-margin-start": CSSLengthPercentageValue,
    "-webkit-margin-top-collapse": WebkitMarginAfterCollapseValue,
    "-webkit-marquee-speed": WebkitMarqueeSpeedValue,
    "-webkit-mask": MaskValue,
    "-webkit-mask-box-image": MaskBorderValue,
    "-webkit-mask-box-image-outset": BorderImageOutsetValue,
    "-webkit-mask-box-image-repeat": BorderImageRepeatValue,
    "-webkit-mask-box-image-slice": BorderImageSliceValue,
    "-webkit-mask-box-image-source": ImageValue,
    "-webkit-mask-box-image-width": BorderImageWidthValue,
    "-webkit-mask-clip": MaskClipValue,
    "-webkit-mask-composite": MaskCompositeValue,
    "-webkit-mask-origin": MaskOriginValue,
    "-webkit-mask-position": MaskPositionValue,
    "-webkit-mask-repeat": MaskRepeatValue,
    "-webkit-mask-repeat-x": WebkitMaskRepeatXValue,
    "-webkit-mask-repeat-y": WebkitMaskRepeatXValue,
    "-webkit-mask-size": MaskSizeValue,
    "-webkit-mask-source-type": MaskSourceTypeValue,
    "-webkit-min-logical-height": CSSLengthValue,
    "-webkit-nbsp-mode": WebkitNbspModeValue,
    "-webkit-opacity": OpacityValue,
    "-webkit-overflow-scrolling": WebkitOverflowScrollingValue,
    "-webkit-padding-after": CSSLengthPercentageValue,
    "-webkit-padding-before": CSSLengthPercentageValue,
    "-webkit-padding-end": CSSLengthPercentageValue,
    "-webkit-padding-start": CSSLengthPercentageValue,
    "-webkit-perspective": PerspectiveValue,
    "-webkit-perspective-origin": PerspectiveOriginValue,
    "-webkit-perspective-origin-x": CSSLengthPercentageValue,
    "-webkit-perspective-origin-y": CSSLengthPercentageValue,
    "-webkit-print-color-adjust": WebkitPrintColorAdjustValue,
    "-webkit-rtl-ordering": WebkitRtlOrderingValue,
    "-webkit-ruby-position": WebkitRubyPositionValue,
    "-webkit-shape-margin": CSSLengthPercentageValue,
    "-webkit-shape-outside": ShapeOutsideValue,
    "-webkit-tap-highlight-color": CSSColorValue,
    "-webkit-text-combine": WebkitTextCombineValue,
    "-webkit-text-emphasis": TextEmphasisValue,
    "-webkit-text-emphasis-color": CSSColorValue,
    "-webkit-text-emphasis-position": TextEmphasisPositionValue,
    "-webkit-text-emphasis-style": TextEmphasisStyleValue,
    "-webkit-text-fill-color": CSSColorValue,
    "-webkit-text-orientation": TextOrientationValue,
    "-webkit-text-security": WebkitTextSecurityValue,
    "-webkit-text-stroke": WebkitTextStrokeValue,
    "-webkit-text-stroke-color": WebkitTextStrokeColorValue,
    "-webkit-text-stroke-width": WebkitTextStrokeWidthValue,
    "-webkit-transform": TransformValue,
    "-webkit-transform-origin": TransformOriginValue,
    "-webkit-transform-style": TransformStyleValue,
    "-webkit-transition": TransitionValue,
    "-webkit-transition-delay": common.ClockValue,
    "-webkit-transition-duration": common.ClockValue,
    "-webkit-transition-property": TransitionPropertyValue,
    "-webkit-transition-timing-function": TransitionTimingFunctionValue,
    "-webkit-user-drag": WebkitUserDragValue,
    "-webkit-user-modify": WebkitUserModifyValue,
    "-webkit-user-select": UserSelectValue,
    "-webkit-wrap-flow": WebkitWrapFlowValue,
    "-webkit-writing-mode": WritingModeValue,
    "align-content": AlignContentValue,
    "align-items": AlignItemsValue,
    "align-self": AlignSelfValue,
    # "all": AllValue,
    "animation": AnimationValue,
    "animation-delay": AnimationDelayValue,
    "animation-direction": AnimationDirectionValue,
    "animation-duration": AnimationDurationValue,
    "animation-fill-mode": AnimationFillModeValue,
    "animation-iteration-count": AnimationIterationCountValue,
    "animation-name": AnimationNameValue,
    "animation-play-state": AnimationPlayStateValue,
    "animation-timing-function": AnimationTimingFunctionValue,
    "appearance": AppearanceValue,
    "backdrop-filter": FilterValue,
    "backface-visibility": BackfaceVisibilityValue,
    "background": BackgroundValue,
    "background-attachment": BackgroundAttachmentValue,
    "background-blend-mode": BackgroundBlendModeValue,
    "background-clip": BackgroundClipValue,
    "background-color": CSSColorValue,
    "background-image": ImageValue,
    "background-origin": BackgroundOriginValue,
    "background-position": BackgroundPositionValue,
    "background-position-x": BackgroundPositionXValue,
    "background-position-y": BackgroundPositionYValue,
    "background-repeat": BackgroundRepeatValue,
    "background-repeat-x": BackgroundRepeatXValue,
    "background-repeat-y": BackgroundRepeatXValue,
    "background-size": BackgroundSizeValue,
    "border": BorderValue,
    "border-bottom": LineValue,
    "border-bottom-color": CSSColorValue,
    "border-bottom-left-radius": RadiusValue,
    "border-bottom-right-radius": RadiusValue,
    "border-bottom-style": LineStyleValue,
    "border-bottom-width": CSSLineWidthValue,
    "border-collapse": BorderCollapseValue,
    "border-color": CSSColorValue,
    "border-image": BorderImageValue,
    "border-image-outset": BorderImageOutsetValue,
    "border-image-repeat": BorderImageRepeatValue,
    "border-image-slice": BorderImageSliceValue,
    "border-image-source": ImageValue,
    "border-image-width": BorderImageWidthValue,
    "border-left": LineValue,
    "border-left-color": CSSColorValue,
    "border-left-style": LineStyleValue,
    "border-left-width": CSSLineWidthValue,
    "border-radius": BorderRadiusValue,
    "border-right": LineValue,
    "border-right-color": CSSColorValue,
    "border-right-style": LineStyleValue,
    "border-right-width": CSSLineWidthValue,
    "border-spacing": BorderSpacingValue,
    "border-style": BorderStyleValue,
    "border-top": LineValue,
    "border-top-color": CSSColorValue,
    "border-top-left-radius": RadiusValue,
    "border-top-right-radius": RadiusValue,
    "border-top-style": LineStyleValue,
    "border-top-width": CSSLineWidthValue,
    "border-width": BorderWidthValue,
    "bottom": BottomValue,
    "box-align": BoxAlignValue,
    "box-decoration-break": BoxDecorationBreakValue,
    "box-direction": BoxDirectionValue,
    "box-flex": common.NumberValue,
    "box-flex-group": common.IntegerValue,
    "box-lines": BoxLinesValue,
    "box-ordinal-group": common.IntegerValue,
    "box-orient": BoxOrientValue,
    "box-pack": BoxPackValue,
    "box-reflect": BoxReflectValue,
    "box-shadow": BoxShadowValue,
    "box-sizing": BoxSizingValue,
    "break-after": BreakValue,
    "break-before": BreakValue,
    "break-inside": BreakInsideValue,
    "caption-side": CaptionSideValue,
    "clear": ClearValue,
    "clip": ClipValue,
    "clip-path": ClipPathValue,
    "color": CSSColorValue,
    "column-break-after": ColumnBreakAfterValue,
    "column-break-before": ColumnBreakAfterValue,
    "column-count": ColumnCountValue,
    "column-fill": ColumnFillValue,
    "column-gap": ColumnGapValue,
    "column-rule": BorderValue,
    "column-rule-style": BorderStyleValue,
    "column-rule-color": CSSColorValue,
    "column-rule-width": CSSLineWidthValue,
    "column-span": ColumnSpanValue,
    "column-width": ColumnWidthValue,
    "columns": ColumnsValue,
    "contain": ContainValue,
    "content": ContentValue,
    "counter-increment": CounterIncrementValue,
    "counter-reset": CounterIncrementValue,
    "cursor": CursorValue,
    "direction": DirectionValue,
    "display": DisplayValue,
    "empty-cells": EmptyCellsValue,
    "filter": FilterValue,
    "flex": FlexValue,
    "flex-basis": FlexBasisValue,
    "flex-direction": FlexDirectionValue,
    "flex-flow": FlexFlowValue,
    "flex-grow": common.NumberValue,
    "flex-shrink": common.NumberValue,
    "flex-wrap": FlexWrapValue,
    "float": FloatValue,
    "font": FontValue,
    "font-family": FontFamilyValue,
    "font-feature-settings": FontFeatureSettingsValue,
    "font-smooth": FontSmoothValue,
    "font-kerning": FontKerningValue,
    "font-size": FontSizeValue,
    "font-size-adjust": FontSizeAdjustValue,
    "font-stretch": FontStretchValue,
    "font-style": FontStyleValue,
    "font-variant": FontVariantValue,
    "font-variant-caps": FontVariantCapsValue,
    "font-variant-ligatures": FontVariantLigaturesValue,
    "font-weight": FontWeightValue,
    "grid": GridValue,
    "grid-area": GridAreaValue,
    "grid-auto-columns": GridAutoRowsColumnsValue,
    "grid-auto-flow": GridAutoFlowValue,
    "grid-auto-rows": GridAutoRowsColumnsValue,
    "grid-column": GridRowValue,
    "grid-column-end": GridLineValue,
    "grid-column-gap": GridLineGapValue,
    "grid-column-start": GridLineValue,
    "grid-gap": GridGapValue,
    "grid-row": GridRowValue,
    "grid-row-end": GridLineValue,
    "grid-row-gap": GridLineGapValue,
    "grid-row-start": GridLineValue,
    "grid-template": GridTemplateValue,
    "grid-template-areas": GridTemplateAreasValue,
    "grid-template-columns": GridTemplateRowsColumnsValue,
    "grid-template-rows": GridTemplateRowsColumnsValue,
    "height": HeightValue,
    "hyphens": HyphensValue,
    "image-orientation": ImageOrientationValue,
    "image-rendering": ImageRenderingValue,
    "isolation": IsolationValue,
    "justify-content": JustifyContentValue,
    "justify-items": JustifyItemsValue,
    "justify-self": JustifySelfValue,
    "kerning": KerningValue,
    "left": BottomValue,
    "letter-spacing": LetterSpacingValue,
    "line-break": LineBreakValue,
    "line-height": LineHeightValue,
    "list-style": ListStyleValue,
    "list-style-image": ListStyleImageValue,
    "list-style-position": ListStylePositionValue,
    "list-style-type": ListStyleTypeValue,
    "margin": MarginValue,
    "margin-bottom": BottomValue,
    "margin-left": BottomValue,
    "margin-right": BottomValue,
    "margin-top": BottomValue,
    "mask": MaskValue,
    "mask-clip": MaskClipValue,
    "mask-composite": MaskCompositeValue,
    "mask-image": MaskImageValue,
    "mask-origin": MaskOriginValue,
    "mask-position": MaskPositionValue,
    "mask-repeat": MaskRepeatValue,
    "mask-size": MaskSizeValue,
    "mask-source-type": MaskSourceTypeValue,
    "max-height": HeightValue,
    "max-width": HeightValue,
    "min-height": HeightValue,
    "min-width": HeightValue,
    "max-zoom": MaxZoomValue,
    "mix-blend-mode": BlendModeValue,
    "object-fit": ObjectFitValue,
    "object-position": PositionValue,
    # "offset": OffsetValue,
    # "offset-anchor": OffsetAnchorValue,
    # "offset-distance": CSSLengthPercentageValue,
    # "offset-path": OffsetPathValue,
    # "offset-position": OffsetPositionValue,
    # "offset-rotate": OffsetRotateValue,
    # "offset-rotation": OffsetRotateValue,
    "opacity": OpacityValue,
    "order": common.IntegerValue,
    "orphans": common.IntegerValue,
    "outline": OutlineValue,
    "outline-color": OutlineColorValue,
    "outline-offset": CSSLengthValue,
    "outline-style": OutlineStyleValue,
    "outline-width": CSSLineWidthValue,
    "overflow": OverflowValue,
    "overflow-anchor": OverflowAnchorValue,
    "overflow-wrap": OverflowWrapValue,
    "overflow-x": OverflowXValue,
    "overflow-y": OverflowXValue,
    "padding": PaddingValue,
    "padding-bottom": BottomValue,
    "padding-left": BottomValue,
    "padding-right": BottomValue,
    "padding-top": BottomValue,
    "page": PageValue,
    "page-break-after": BreakValue,
    "page-break-before": BreakValue,
    "page-break-inside": BreakInsideValue,
    "perspective": PerspectiveValue,
    "perspective-origin": PerspectiveOriginValue,
    "pointer-events": PointerEventsValue,
    "position": PositionWayValue,
    "prince-hyphens": PrinceHyphensValue,
    "quotes": QuotesValue,
    "resize": ResizeValue,
    "right": BottomValue,
    "rotate": RotateValue,
    "rotation": common.AngleValue,
    "scale": ScaleValue,
    "scroll-behavior": ScrollBehaviorValue,
    "scroll-snap-coordinate": ScrollSnapCoordinateValue,
    "scroll-snap-destination": PositionValue,
    "scroll-snap-points-x": ScrollSnapPointsXValue,
    "scroll-snap-points-y": ScrollSnapPointsXValue,
    "scroll-snap-type": ScrollSnapTypeValue,
    "shape-image-threshold": ShapeImageThresholdValue,
    "shape-margin": CSSLengthPercentageValue,
    "shape-outside": ShapeOutsideValue,
    "tab-size": common.IntegerLengthValue,
    "table-layout": TableLayoutValue,
    "text-align": TextAlignValue,
    "text-align-last": TextAlignLastValue,
    "text-combine-upright": TextCombineUprightValue,
    "text-decoration": TextDecorationValue,
    "text-decoration-color": CSSColorValue,
    "text-decoration-line": TextDecorationLineValue,
    "text-decoration-skip": TextDecorationSkipValue,
    "text-decoration-style": TextDecorationStyleValue,
    "text-decoration-thickness": TextDecorationThicknessValue,
    "text-emphasis": TextEmphasisValue,
    "text-emphasis-color": CSSColorValue,
    "text-emphasis-position": TextEmphasisPositionValue,
    "text-emphasis-style": TextEmphasisStyleValue,
    "text-indent": TextIndentValue,
    "text-justify": TextJustifyValue,
    "text-orientation": TextOrientationValue,
    "text-overflow": TextOverflowValue,
    "text-rendering": TextRenderingValue,
    "text-shadow": TextShadowValue,
    "text-transform": TextTransformValue,
    "text-underline": TextUnderlineValue,
    "text-underline-position": TextUnderlinePositionValue,
    "text-underline-color": CSSColorValue,
    "text-underline-mode": TextUnderlineModeValue,
    "text-underline-style": TextUnderlineStyleValue,
    "text-underline-width": TextUnderlineWidthValue,
    "text-underline-offset": TextUnderlineOffsetValue,
    "top": BottomValue,
    "touch-action": TouchActionValue,
    "transform": TransformValue,
    "transform-origin": TransformOriginValue,
    "transform-style": TransformStyleValue,
    "transition": TransitionValue,
    "transition-delay": common.ClockValue,
    "transition-duration": common.ClockValue,
    "transition-property": TransitionPropertyValue,
    "transition-timing-function": TransitionTimingFunctionValue,
    "translate": TranslateValue,
    "unicode-bidi": UnicodeBidiValue,
    "user-select": UserSelectValue,
    "user-zoom": UserZoomValue,
    "vertical-align": VerticalAlignValue,
    "visibility": VisibilityValue,
    "white-space": WhiteSpaceValue,
    "widows": common.IntegerValue,
    "width": HeightValue,
    "will-change": WillChangeValue,
    "word-break": WordBreakValue,
    "word-spacing": WordSpacingValue,
    "word-wrap": OverflowWrapValue,
    "writing-mode": WritingModeValue,
    "z-index": ZIndexValue,
    "zoom": ZoomValue,
    "-webkit-mask-image": MaskImageValue,
    "-webkit-text-decorations-in-effect": WebkitTextDecorationInEffectValue,
    # "border-end-end-radius": RadiusValue,
    # "border-end-start-radius": RadiusValue,
    # "border-start-end-radius": RadiusValue,
    # "border-start-start-radius": RadiusValue,
    "caret-color": CaretColorValue,
    "font-variation-settings": FontVariationSettingsValue,
    "gap": GridGapValue,
    "inset": InsetValue,
    "inset-block": InsetBlockValue,
    "inset-block-end": LocationValue,
    "inset-block-start": LocationValue,
    "inset-inline": InsetInlineValue,
    "inset-inline-end": LocationValue,
    "inset-inline-start": LocationValue,
    # "line-clamp": common.IntegerValue,
    # "mask-border": MaskBorderValue,
    # "mask-border-source": ImageValue,
    # "mask-border-slice": BorderImageSliceValue,
    # "mask-border-width": BorderImageWidthValue,
    # "mask-border-outset": BorderImageOutsetValue,
    # "mask-border-repeat": BorderImageRepeatValue,
    # "mask-border-mode": MaskBorderModeValue,
    # "max-lines": common.IntegerValue,
    "row-gap": GridLineGapValue,
    # "scroll-margin": ScrollMarginValue,
    # "scroll-margin-block": ScrollMarginBlockValue,
    # "scroll-margin-block-end": CSSLengthValue,
    # "scroll-margin-block-start": CSSLengthValue,
    # "scroll-margin-bottom": CSSLengthValue,
    # "scroll-margin-inline": ScrollMarginInlineValue,
    # "scroll-margin-inline-end": CSSLengthValue,
    # "scroll-margin-inline-start": CSSLengthValue,
    # "scroll-margin-left": CSSLengthValue,
    # "scroll-margin-right": CSSLengthValue,
    # "scroll-margin-top": CSSLengthValue,
    "scroll-padding": ScrollPaddingValue,
    "scroll-padding-block": ScrollPaddingBlockValue,
    "scroll-padding-block-end": ScrollPaddingLineValue,
    "scroll-padding-block-start": ScrollPaddingLineValue,
    "scroll-padding-bottom": ScrollPaddingLineValue,
    "scroll-padding-inline": ScrollPaddingInlineValue,
    "scroll-padding-inline-end": ScrollPaddingLineValue,
    "scroll-padding-inline-start": ScrollPaddingLineValue,
    "scroll-padding-left": ScrollPaddingLineValue,
    "scroll-padding-right": ScrollPaddingLineValue,
    "scroll-padding-top": ScrollPaddingLineValue,
    # "scrollbar-color": ScrollbarColorValue,
}


def get_css_property(animatable=False):
    if animatable:
        prop = Random.choice(docs.css_animatable_properties)
    else:
        prop = Random.choice(list(css_properties.keys()))
    return prop, css_properties[prop]


def get_css_property_value(prop):
    return css_properties.get(prop)


def get_css_property_name():
    return Random.choice(list(css_properties.keys()))
