CSS_ANIMATABLE_PROPERTIES = [
    "-webkit-background-size",
    "-webkit-border-bottom-left-radius",
    "-webkit-border-bottom-right-radius",
    "-webkit-border-radius",
    "-webkit-border-top-left-radius",
    "-webkit-border-top-right-radius",
    "-webkit-box-shadow",
    "-webkit-clip-path",
    "-webkit-column-count",
    "-webkit-column-gap",
    "-webkit-column-rule",
    "-webkit-column-rule-color",
    "-webkit-column-rule-width",
    "-webkit-column-width",
    "-webkit-columns",
    "-webkit-filter",
    "-webkit-flex",
    "-webkit-line-clamp",
    "-webkit-mask",
    "-webkit-mask-position",
    "-webkit-mask-size",
    "-webkit-opacity",
    "-webkit-perspective",
    "-webkit-perspective-origin",
    "-webkit-shape-margin",
    "-webkit-text-emphasis",
    "-webkit-text-emphasis-color",
    "-webkit-text-fill-color",
    "-webkit-text-stroke",
    "-webkit-text-stroke-color",
    "-webkit-transform",
    "-webkit-transform-origin",
    # "all",
    "backdrop-filter",
    "background",
    "background-color",
    "background-position",
    "background-size",
    "border",
    "border-bottom",
    "border-bottom-color",
    "border-bottom-left-radius",
    "border-bottom-right-radius",
    "border-bottom-width",
    "border-color",
    # "border-end-end-radius",
    # "border-end-start-radius",
    "border-left",
    "border-left-color",
    "border-left-width",
    "border-radius",
    "border-right",
    "border-right-color",
    "border-right-width",
    # "border-start-end-radius",
    # "border-start-start-radius",
    "border-top",
    "border-top-color",
    "border-top-left-radius",
    "border-top-right-radius",
    "border-top-width",
    "border-width",
    "bottom",
    "box-shadow",
    "caret-color",
    "clip",
    "clip-path",
    "color",
    "column-count",
    "column-gap",
    "column-rule",
    "column-rule-color",
    "column-rule-width",
    "column-width",
    "columns",
    "filter",
    "flex",
    "flex-basis",
    "flex-grow",
    "flex-shrink",
    "font",
    "font-size",
    "font-size-adjust",
    "font-stretch",
    "font-variation-settings",
    "font-weight",
    "gap",
    "grid-column-gap",
    "grid-gap",
    "grid-row-gap",
    "grid-template-columns",
    "grid-template-rows",
    "height",
    "inset",
    "inset-block",
    "inset-block-end",
    "inset-block-start",
    "inset-inline",
    "inset-inline-end",
    "inset-inline-start",
    "left",
    "letter-spacing",
    # "line-clamp",
    "line-height",
    "margin",
    "margin-bottom",
    "margin-left",
    "margin-right",
    "margin-top",
    "mask",
    # "mask-border",
    # "mask-border-mode",
    # "mask-border-outset",
    # "mask-border-repeat",
    # "mask-border-slice",
    # "mask-border-source",
    # "mask-border-width",
    "mask-position",
    "mask-size",
    "max-height",
    # "max-lines",
    "max-width",
    "min-height",
    "min-width",
    "object-position",
    # "offset",
    # "offset-anchor",
    # "offset-distance",
    # "offset-path",
    # "offset-position",
    # "offset-rotate",
    # "offset-rotation",
    "opacity",
    "order",
    "outline",
    "outline-color",
    "outline-offset",
    "outline-width",
    "padding",
    "padding-bottom",
    "padding-left",
    "padding-right",
    "padding-top",
    "perspective",
    "perspective-origin",
    "right",
    "rotate",
    "row-gap",
    "scale",
    # "scroll-margin",
    # "scroll-margin-block",
    # "scroll-margin-block-end",
    # "scroll-margin-block-start",
    # "scroll-margin-bottom",
    # "scroll-margin-inline",
    # "scroll-margin-inline-end",
    # "scroll-margin-inline-start",
    # "scroll-margin-left",
    # "scroll-margin-right",
    # "scroll-margin-top",
    "scroll-padding",
    "scroll-padding-block",
    "scroll-padding-block-end",
    "scroll-padding-block-start",
    "scroll-padding-bottom",
    "scroll-padding-inline",
    "scroll-padding-inline-end",
    "scroll-padding-inline-start",
    "scroll-padding-left",
    "scroll-padding-right",
    "scroll-padding-top",
    "scroll-snap-coordinate",
    "scroll-snap-destination",
    # "scrollbar-color",
    "shape-image-threshold",
    "shape-margin",
    "shape-outside",
    "tab-size",
    "text-decoration",
    "text-decoration-color",
    "text-emphasis",
    "text-emphasis-color",
    "text-indent",
    "text-shadow",
    "top",
    "transform",
    "transform-origin",
    "translate",
    "vertical-align",
    "visibility",
    "width",
    "word-spacing",
    "z-index",
    "zoom"
]
