PARENTS = {
    "DocumentTimeline": ["AnimationTimeline"],
    "AnimationEffectTiming": ["AnimationEffectTimingReadOnly"],
    "KeyframeEffectReadOnly": ["AnimationEffectReadOnly"],
    "KeyframeEffect": ["KeyframeEffectReadOnly"],

    "VTTCue": ["TextTrackCue"],

    "Comment": ["CharacterData"],
    "Text": ["CharacterData"],
    "CDATASection": ["Text"],
    "CharacterData": ["Element"],
    "ProcessingInstruction": ["CharacterData"],
    "DocumentFragment": ["Element"],
    "Document": ["DocumentOrShadowRoot", "EventTarget"],
    "ShadowRoot": ["DocumentOrShadowRoot", "DocumentFragment"],

    "Element": ["EventTarget"],
    "Window": ["EventTarget"],

    # CSS
    "CSSStyleSheet": ["StyleSheet"],
    "CSSKeyframesSheet": ["StyleSheet"],
    "CSSStyleRule": ["CSSRule"],
    "CSSKeyframesRule": ["CSSRule"],
    "CSSKeyframeRule": ["CSSRule"],

    # Event
    "ResourceProgressEvent": ["ProgressEvent"],

    "CustomEvent": ["Event"],
    "MediaQueryListEvent": ["Event"],
    "ApplicationCacheErrorEvent": ["Event"],
    "SecurityPolicyViolationEvent": ["Event"],
    "BeforeUnloadEvent": ["Event"],
    "UIEvent": ["Event"],
    "PointerEvent": ["MouseEvent"],
    "PromiseRejectionEvent": ["Event"],
    "FocusEvent": ["UIEvent"],
    "CompositionEvent": ["UIEvent"],
    "InputEvent": ["UIEvent"],
    "TextEvent": ["UIEvent"],
    "ClipboardEvent": ["Event"],
    "ProgressEvent": ["Event"],
    "WheelEvent": ["MouseEvent"],
    "HashChangeEvent": ["Event"],
    "MouseEvent": ["UIEvent"],
    "TransitionEvent": ["Event"],
    "AnimationPlaybackEvent": ["Event"],
    "PopStateEvent": ["Event"],
    "DragEvent": ["MouseEvent"],
    "PageTransitionEvent": ["Event"],
    "MessageEvent": ["Event"],
    "MutationEvent": ["Event"],
    "AnimationEvent": ["Event"],
    "ErrorEvent": ["Event"],
    "KeyboardEvent": ["UIEvent"],

    # HTML
    "HTMLElement": ["Element"],
    "HTMLMediaElement": ["HTMLElement"],
    "HTMLQuoteElement": ["HTMLElement"],
    "HTMLModElement": ["HTMLElement"],
    "HTMLHeadingElement": ["HTMLElement"],
    "HTMLTableSectionElement": ["HTMLElement"],

    "HTMLAnchorElement": ["HTMLElement"],
    "HTMLAbbrElement": ["HTMLElement"],
    "HTMLAcronymElement": ["HTMLElement"],
    "HTMLAddressElement": ["HTMLElement"],
    "HTMLAreaElement": ["HTMLElement"],
    "HTMLArticleElement": ["HTMLElement", "ShadowHost"],
    "HTMLAsideElement": ["HTMLElement", "ShadowHost"],
    "HTMLAudioElement": ["HTMLMediaElement"],
    "HTMLBElement": ["HTMLElement"],
    "HTMLBaseElement": ["HTMLElement"],
    "HTMLBaseFontElement": ["HTMLElement"],
    "HTMLBDIElement": ["HTMLElement"],
    "HTMLBDOElement": ["HTMLElement"],
    "HTMLBgSoundElement": ["HTMLElement"],
    "HTMLBigElement": ["HTMLElement"],
    "HTMLBlockQuoteElement": ["HTMLQuoteElement", "ShadowHost"],
    "HTMLBodyElement": ["HTMLElement", "ShadowHost"],
    "HTMLBRElement": ["HTMLElement"],
    "HTMLButtonElement": ["HTMLElement"],
    "HTMLCanvasElement": ["HTMLElement"],
    "HTMLTableCaptionElement": ["HTMLElement"],
    "HTMLCenterElement": ["HTMLElement"],
    "HTMLCiteElement": ["HTMLElement"],
    "HTMLCodeElement": ["HTMLElement"],
    "HTMLTableColElement": ["HTMLElement"],
    "HTMLTableColGroupElement": ["HTMLTableColElement"],
    "HTMLCommandElement": ["HTMLElement"],
    "HTMLContentElement": ["HTMLElement"],
    "HTMLDataElement": ["HTMLElement"],
    "HTMLDataListElement": ["HTMLElement"],
    "HTMLDDElement": ["HTMLElement"],
    "HTMLDelElement": ["HTMLModElement"],
    "HTMLDetailsElement": ["HTMLElement"],
    "HTMLDFNElement": ["HTMLElement"],
    "HTMLDialogElement": ["HTMLElement"],
    "HTMLDirectoryElement": ["HTMLElement"],
    "HTMLDivElement": ["HTMLElement", "ShadowHost"],
    "HTMLDListElement": ["HTMLElement"],
    "HTMLDTElement": ["HTMLElement"],
    "HTMLEMElement": ["HTMLElement"],
    "HTMLEmbedElement": ["HTMLElement"],
    "HTMLFieldSetElement": ["HTMLElement"],
    "HTMLFigCaptionElement": ["HTMLElement"],
    "HTMLFigureElement": ["HTMLElement"],
    "HTMLFontElement": ["HTMLElement"],
    "HTMLFooterElement": ["HTMLElement", "ShadowHost"],
    "HTMLFormElement": ["HTMLElement"],
    "HTMLFrameElement": ["HTMLElement"],
    "HTMLFrameSetElement": ["HTMLElement"],
    "HTMLHeading1Element": ["HTMLHeadingElement", "ShadowHost"],
    "HTMLHeading2Element": ["HTMLHeadingElement", "ShadowHost"],
    "HTMLHeading3Element": ["HTMLHeadingElement", "ShadowHost"],
    "HTMLHeading4Element": ["HTMLHeadingElement", "ShadowHost"],
    "HTMLHeading5Element": ["HTMLHeadingElement", "ShadowHost"],
    "HTMLHeading6Element": ["HTMLHeadingElement", "ShadowHost"],
    "HTMLHeadElement": ["HTMLElement"],
    "HTMLHeaderElement": ["HTMLElement", "ShadowHost"],
    "HTMLHGroupElement": ["HTMLElement"],
    "HTMLHRElement": ["HTMLElement"],
    "HTMLHtmlElement": ["HTMLElement"],
    "HTMLIElement": ["HTMLElement"],
    "HTMLIFrameElement": ["HTMLElement"],
    "HTMLImageElement": ["HTMLElement"],
    "HTMLInputElement": ["HTMLElement"],
    "HTMLInsElement": ["HTMLModElement"],
    "HTMLIsIndexElement": ["HTMLElement"],
    "HTMLKBDElement": ["HTMLElement"],
    "HTMLKeygenElement": ["HTMLElement"],
    "HTMLLabelElement": ["HTMLElement"],
    "HTMLLegendElement": ["HTMLElement"],
    "HTMLLIElement": ["HTMLElement"],
    "HTMLLinkElement": ["HTMLElement"],
    "HTMLListingElement": ["HTMLElement"],
    "HTMLMainElement": ["HTMLElement", "ShadowHost"],
    "HTMLMapElement": ["HTMLElement"],
    "HTMLMarkElement": ["HTMLElement"],
    "HTMLMarqueeElement": ["HTMLElement"],
    "HTMLMenuElement": ["HTMLElement"],
    "HTMLMenuItemElement": ["HTMLElement"],
    "HTMLMetaElement": ["HTMLElement"],
    "HTMLMeterElement": ["HTMLElement"],
    "HTMLNavElement": ["HTMLElement", "ShadowHost"],
    "HTMLObjectElement": ["HTMLElement"],
    "HTMLOListElement": ["HTMLElement"],
    "HTMLOptGroupElement": ["HTMLElement"],
    "HTMLOptionElement": ["HTMLElement"],
    "HTMLOutputElement": ["HTMLElement"],
    "HTMLParagraphElement": ["HTMLElement", "ShadowHost"],
    "HTMLParamElement": ["HTMLElement"],
    "HTMLPictureElement": ["HTMLElement"],
    "HTMLPlainTextElement": ["HTMLElement"],
    "HTMLPreElement": ["HTMLElement"],
    "HTMLProgressElement": ["HTMLElement"],
    "HTMLQElement": ["HTMLQuoteElement"],
    "HTMLRPElement": ["HTMLElement"],
    "HTMLRTElement": ["HTMLElement"],
    "HTMLRubyElement": ["HTMLElement"],
    "HTMLSElement": ["HTMLElement"],
    "HTMLSampElement": ["HTMLElement"],
    "HTMLScriptElement": ["HTMLElement"],
    "HTMLSectionElement": ["HTMLElement", "ShadowHost"],
    "HTMLSelectElement": ["HTMLElement"],
    "HTMLShadowElement": ["HTMLElement"],
    "HTMLSlotElement": ["HTMLElement"],
    "HTMLSmallElement": ["HTMLElement"],
    "HTMLSourceElement": ["HTMLElement"],
    "HTMLSpanElement": ["HTMLElement", "ShadowHost"],
    "HTMLStrikeElement": ["HTMLElement"],
    "HTMLStrongElement": ["HTMLElement"],
    "HTMLStyleElement": ["HTMLElement"],
    "HTMLSubElement": ["HTMLElement"],
    "HTMLSummaryElement": ["HTMLElement"],
    "HTMLSupElement": ["HTMLElement"],
    "HTMLTimeElement": ["HTMLElement"],
    "HTMLTableElement": ["HTMLElement"],
    "HTMLTBodyElement": ["HTMLTableSectionElement"],
    "HTMLTableDataCellElement": ["HTMLTableCellElement", "HTMLElement"],
    "HTMLTemplateElement": ["HTMLElement"],
    "HTMLTextAreaElement": ["HTMLElement"],
    "HTMLTFootElement": ["HTMLTableSectionElement"],
    "HTMLTableHeaderCellElement": ["HTMLTableCellElement", "HTMLElement"],
    "HTMLTHeadElement": ["HTMLTableSectionElement"],
    "HTMLTitleElement": ["HTMLElement"],
    "HTMLTableRowElement": ["HTMLElement"],
    "HTMLTrackElement": ["HTMLElement"],
    "HTMLTTElement": ["HTMLElement"],
    "HTMLUElement": ["HTMLElement"],
    "HTMLUListElement": ["HTMLElement"],
    "HTMLVarElement": ["HTMLElement"],
    "HTMLVideoElement": ["HTMLMediaElement"],
    "HTMLWBRElement": ["HTMLElement"],
    "HTMLXMPElement": ["HTMLElement"],

    # SVG
    "SVGElement": ["Element"],
    "SVGViewSpec": ["SVGFitToViewBox", "SVGZoomAndPan"],
    "SVGAElement": ["SVGGraphicsElement", "SVGURIReference"],
    "SVGAltGlyphDefElement": ["SVGElement"],
    "SVGAltGlyphElement": ["SVGGraphicsElement", "SVGURIReference"],
    "SVGAltGlyphItemElement": ["SVGElement"],
    "SVGAnimateColorElement": ["SVGAnimationElement"],
    "SVGAnimateElement": ["SVGAnimationElement"],
    "SVGAnimateMotionElement": ["SVGAnimationElement"],
    "SVGAnimateTransformElement": ["SVGAnimationElement"],
    "SVGAnimationElement": ["SVGElement"],
    "SVGCircleElement": ["SVGGeometryElement"],
    "SVGClipPathElement": ["SVGElement"],
    "SVGColorProfileElement": ["SVGElement", "SVGURIReference"],
    "SVGComponentTransferFunctionElement": ["SVGElement"],
    "SVGCursorElement": ["SVGElement", "SVGURIReference"],
    "SVGDefsElement": ["SVGGraphicsElement"],
    "SVGDescElement": ["SVGElement"],
    "SVGDiscardElement": ["SVGElement"],
    "SVGEllipseElement": ["SVGGeometryElement"],
    "SVGFEBlendElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEColorMatrixElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEComponentTransferElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFECompositeElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEConvolveMatrixElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEDiffuseLightingElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEDisplacementMapElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEDistantLightElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEDropShadowElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEFloodElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEFuncAElement": ["SVGComponentTransferFunctionElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEFuncBElement": ["SVGComponentTransferFunctionElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEFuncGElement": ["SVGComponentTransferFunctionElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEFuncRElement": ["SVGComponentTransferFunctionElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEGaussianBlurElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEImageElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes", "SVGURIReference"],
    "SVGFEMergeElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEMergeNodeElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEMorphologyElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEOffsetElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFEPointLightElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFESpecularLightingElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFESpotLightElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFETileElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFETurbulenceElement": ["SVGElement", "SVGFilterPrimitiveStandardAttributes"],
    "SVGFilterElement": ["SVGElement", "SVGURIReference"],
    "SVGFontElement": ["SVGElement"],
    "SVGFontFaceElement": ["SVGElement"],
    "SVGFontFaceFormatElement": ["SVGElement"],
    "SVGFontFaceNameElement": ["SVGElement"],
    "SVGFontFaceSrcElement": ["SVGElement"],
    "SVGFontFaceUriElement": ["SVGElement"],
    "SVGForeignObjectElement": ["SVGGraphicsElement"],
    "SVGGElement": ["SVGGraphicsElement"],
    "SVGGeometryElement": ["SVGGraphicsElement"],
    "SVGGlyphElement": ["SVGElement"],
    "SVGGlyphRefElement": ["SVGElement", "SVGURIReference"],
    "SVGGradientElement": ["SVGElement", "SVGURIReference"],
    "SVGGraphicsElement": ["SVGElement"],
    "SVGHKernElement": ["SVGElement"],
    "SVGHatchElement": ["SVGElement"],
    "SVGHatchpathElement": ["SVGElement"],
    "SVGImageElement": ["SVGGraphicsElement", "SVGURIReference"],
    "SVGLineElement": ["SVGGeometryElement"],
    "SVGLinearGradientElement": ["SVGGradientElement"],
    "SVGMPathElement": ["SVGElement", "SVGURIReference"],
    "SVGMarkerElement": ["SVGElement", "SVGFitToViewBox"],
    "SVGMaskElement": ["SVGElement"],
    "SVGMetadataElement": ["SVGElement"],
    "SVGMissingGlyphElement": ["SVGElement"],
    "SVGPathElement": ["SVGGeometryElement"],
    "SVGPatternElement": ["SVGElement", "SVGFitToViewBox", "SVGURIReference"],
    "SVGPolygonElement": ["SVGGeometryElement"],
    "SVGPolylineElement": ["SVGGeometryElement"],
    "SVGRadialGradientElement": ["SVGGradientElement"],
    "SVGRectElement": ["SVGGeometryElement"],
    "SVGSVGElement": ["SVGGraphicsElement", "SVGFitToViewBox", "SVGZoomAndPan"],
    "SVGScriptElement": ["SVGElement", "SVGURIReference"],
    "SVGSetElement": ["SVGAnimationElement"],
    "SVGSolidcolorElement": ["SVGElement"],
    "SVGStopElement": ["SVGElement"],
    "SVGStyleElement": ["SVGElement"],
    "SVGSwitchElement": ["SVGGraphicsElement"],
    "SVGSymbolElement": ["SVGGraphicsElement", "SVGFitToViewBox"],
    "SVGTRefElement": ["SVGTextPositioningElement", "SVGURIReference"],
    "SVGTSpanElement": ["SVGTextPositioningElement"],
    "SVGTextContentElement": ["SVGGraphicsElement"],
    "SVGTextElement": ["SVGTextPositioningElement"],
    "SVGTextPathElement": ["SVGTextContentElement", "SVGURIReference"],
    "SVGTextPositioningElement": ["SVGTextContentElement"],
    "SVGTitleElement": ["SVGElement"],
    "SVGUseElement": ["SVGGraphicsElement", "SVGURIReference"],
    "SVGVKernElement": ["SVGElement"],
    "SVGViewElement": ["SVGElement", "SVGFitToViewBox", "SVGZoomAndPan"],

    "SVGPathSegArcAbs": ["SVGPathSeg"],
    "SVGPathSegArcRel": ["SVGPathSeg"],
    "SVGPathSegClosePath": ["SVGPathSeg"],
    "SVGPathSegCurvetoCubicAbs": ["SVGPathSeg"],
    "SVGPathSegCurvetoCubicRel": ["SVGPathSeg"],
    "SVGPathSegCurvetoCubicSmoothAbs": ["SVGPathSeg"],
    "SVGPathSegCurvetoCubicSmoothRel": ["SVGPathSeg"],
    "SVGPathSegCurvetoQuadraticAbs": ["SVGPathSeg"],
    "SVGPathSegCurvetoQuadraticRel": ["SVGPathSeg"],
    "SVGPathSegCurvetoQuadraticSmoothAbs": ["SVGPathSeg"],
    "SVGPathSegCurvetoQuadraticSmoothRel": ["SVGPathSeg"],
    "SVGPathSegLinetoAbs": ["SVGPathSeg"],
    "SVGPathSegLinetoHorizontalAbs": ["SVGPathSeg"],
    "SVGPathSegLinetoHorizontalRel": ["SVGPathSeg"],
    "SVGPathSegLinetoRel": ["SVGPathSeg"],
    "SVGPathSegLinetoVerticalAbs": ["SVGPathSeg"],
    "SVGPathSegLinetoVerticalRel": ["SVGPathSeg"],
    "SVGPathSegMovetoAbs": ["SVGPathSeg"],
    "SVGPathSegMovetoRel": ["SVGPathSeg"],
}

if __name__ == "__main__":
    fout = open("hierarchy.py", "w")
    fout.write("# Auto-generated by generate_hierarchy.py\n")

    children = {}

    for x in PARENTS:
        parents = PARENTS[x]
        for parent in parents:
            if parent not in children: children[parent] = []
            children[parent].append(x)


    def get_offspring(x):
        if x not in children:
            return []
        ret = children[x]
        for child in children[x]:
            ret += get_offspring(child)
        return ret


    offsprings = {}
    for parent in children:
        offsprings[parent] = list(set(get_offspring(parent)))

    fout.write("OFFSPRINGS = {\n")
    for parent in sorted(offsprings.keys()):
        fout.write("    \"{0}\": {1},\n".format(parent, str(offsprings[parent]).replace("'", "\"")))
    fout.write("}\n\n")


    def get_ancestors(x):
        if x not in PARENTS:
            return []
        ret = PARENTS[x]
        for p in PARENTS[x]:
            ret += get_ancestors(p)
        return ret


    ancestors = {}
    for x in PARENTS:
        ancestors[x] = list(set(get_ancestors(x)))

    fout.write("ANCESTORS = {\n")
    for x in sorted(ancestors.keys()):
        fout.write("    \"{0}\": {1},\n".format(x, str(ancestors[x]).replace("'", "\"")))
    fout.write("}\n")

    fout.close()
